# Generated by Django 5.0.1 on 2024-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('FS', 'Family Suite'), ('PS', 'Presidential Suite'), ('SS', 'Singles Suite'), ('DS', 'Double Suite'), ('HS', 'Honeymoon Suite'), ('XS', 'Extra Suite')], max_length=2)),
                ('room_title', models.CharField(max_length=100)),
                ('room_price', models.FloatField()),
                ('room_description', models.TextField()),
                ('room_occupants_size', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('room_availability', models.BooleanField()),
            ],
        ),
    ]
